eureka.instance.hostname=localhost
eureka.client.service-ulr.default-zone=http://localhost:8761/eureka
spring.cloud.config.override.system-properties=false
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/note
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
management.info.git.mode=full
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.application.name}
management.tracing.enabled=true
management.zipkin.tracing.endpoint=http://localhost:9411
management.tracing.sampling.probability=1.0
