eureka.instance.hostname=${spring.application.name}
eureka.instance.prefer-ip-address=true
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/note-docker
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

management.zipkin.tracing.endpoint=http://tempo:9411

loki.url=http://loki:3100/loki/api/v1/push