server.port=8092
spring.data.mongodb.uri=mongodb://mongo:mongo@localhost:27017/task?authSource=admin
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.producer.bootstrap-servers=localhost:9092