spring.application.name=tag
spring.config.import=optional:configserver:http://localhost:8888
spring.liquibase.change-log=classpath:/db/db.changelog-master.yaml
spring.profiles.active=dev

#kafka topics
kafka.topic.tag-delete=tag-delete

#kafka
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer