services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - microservices
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - microservices
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - microservices
    depends_on:
      - zookeeper
  akhq:
    container_name: akhq
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
         connections:
           kafka:
             properties:
               bootstrap.servers: "kafka:29092"
    ports:
      - "8080:8080"
    networks:
      - microservices
    depends_on:
      - kafka
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8090:8080"
    networks:
      - microservices
    command:
      - "start-dev"
    volumes:
      - ./keycloak/realm-export.json:/opt/jboss/keycloak/imports/realm-export.json

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command: "--config.file=/etc/prometheus/prometheus.yaml"

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      - ./promtail/promtail-docker-config.yml:/etc/promtail/docker-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: "--config.file=/etc/promtail/docker-config.yml"
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    command: "-config.file=/etc/loki/local-config.yaml"
    ports:
      - "3100:3100"
    depends_on:
      - promtail
  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: "-config.file /etc/tempo-config.yml"
    ports:
      - "3200:3200"
      - "9411:9411"
    volumes:
      - ./tempo/tempo.yml:/etc/tempo-config.yml
  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server
    restart: unless-stopped
networks:
  microservices:
    driver: bridge
volumes:
  postgres:
  mongo:
  grafana_data: { }
